version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo installing npm .............
      - sudo apt install npm -y
      - echo Installing Angular CLI and dependencies...
      - npm install -g @angular/cli
      - npm install

  build:
    commands:
      - echo Building the Angular application...
      - ng build --configuration=production

  post_build:
    commands:
    - echo Uploading build to S3...
    - aws s3 cp dist/angularapp s3://artifacts-buck-angular/ --recursive

 


artifacts:
  files:
    - '**/*'
  base-directory: dist/angularapp


  

 


